# Generated by Django 6.0.6 on 2026-06-15 15:53

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAnalyticsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'github_analytics_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GitHubCacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=200)),
                ('rate_limit_remaining', models.IntegerField()),
                ('rate_limit_reset', models.DateTimeField()),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('public_repos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_fetched'],
                'indexes': [models.Index(fields=['username'], name='api_githubp_usernam_391a8c_idx'), models.Index(fields=['last_fetched'], name='api_githubp_last_fe_589dfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('html_url', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='api.githubprofile')),
            ],
            options={
                'ordering': ['-stargazers_count'],
                'indexes': [models.Index(fields=['profile', '-stargazers_count'], name='api_githubr_profile_3d663f_idx'), models.Index(fields=['language'], name='api_githubr_languag_a01b3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.JSONField(default=dict)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_stats', to='api.githubprofile')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['languages'], name='lang_stats_gin_idx')],
            },
        ),
    ]
