# Generated by Django 6.0.6 on 2026-06-16 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubcachelog',
            name='rate_limit_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
